### Linear Regression Model Testing

In [1]:
import pandas as pd
import numpy as np
import pickle
import json

#### Load Model

In [2]:
with open("Linear_reg_model.pkl", "rb") as f:
    model = pickle.load(f)
model

LinearRegression()

In [9]:
with open("label_encoded_data.json", "r") as f:
    label_enc_data = json.load(f)
label_enc_data

{'gender': {'male': 1, 'female': 0}, 'smoker': {'yes': 1, 'no': 0}}

In [10]:
column_names = model.feature_names_in_
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [7]:
model.n_features_in_

9

In [4]:
model.coef_

array([  259.54736297,  -254.39763573,   353.03769217,   543.28925423,
       24124.10937703,   426.60645499,   234.60398263,  -469.52714954,
        -191.68328808])

### Test Model

In [5]:
age	= 58
gender = "male"
bmi	= 34.89
children = 2
smoker = "yes"
region = "southeast"


In [8]:
test_array = np.zeros((1,model.n_features_in_))
test_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
test_array[0,0] = age
test_array[0,1] = label_enc_data['gender'][gender]
test_array[0,2] = bmi
test_array[0,3] = children
test_array[0,4] = label_enc_data['smoker'][smoker]

region = f"region_{region}"

region_index = np.where(column_names == region)[0]
test_array[0,region_index] = 1
test_array

array([[58.  ,  1.  , 34.89,  2.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ]])

In [21]:
test_df = pd.DataFrame(test_array, columns = column_names)
test_df

age  gender    bmi  children  smoker  region_northeast  region_northwest  \
0  58.0     1.0  34.89       2.0     1.0               0.0               0.0   

   region_southeast  region_southwest  
0               1.0               0.0

In [23]:
predicted_price = model.predict(test_df)[0]
predicted_price
print("Predicted medical insurance price is :",predicted_price)

Predicted medical insurance price is : 38713.81460983026
