### Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import pickle
import warnings
warnings.filterwarnings('ignore')

### Problem Statement

In [ ]:
Predict Medical insurance charges by using age, gender, bmi, children, smoker, region


### Data GAthering

In [2]:
df = pd.read_csv("medical_insurance.csv")
df

age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


### EDA and Feature Engineering

In [4]:
df

age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

##### gender

In [5]:
df['gender'].value_counts()

gender
male      676
female    662
Name: count, dtype: int64

In [6]:
df['gender'].replace({"male":1, "female":0}, inplace = True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   int64  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(3), object(2)
memory usage: 73.3+ KB


##### smoker

In [8]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [9]:
df['smoker'].value_counts().to_dict()

{'no': 1064, 'yes': 274}

In [10]:
df['smoker'].replace({'no': 0, 'yes': 1}, inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   gender    1338 non-null   int64  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int64  
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(4), object(1)
memory usage: 73.3+ KB


##### Region

In [12]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [13]:
df = pd.get_dummies(df, columns= ['region'], dtype = int)
df

age  gender     bmi  children  smoker      charges  region_northeast  \
0      19       0  27.900         0       1  16884.92400                 0   
1      18       1  33.770         1       0   1725.55230                 0   
2      28       1  33.000         3       0   4449.46200                 0   
3      33       1  22.705         0       0  21984.47061                 0   
4      32       1  28.880         0       0   3866.85520                 0   
...   ...     ...     ...       ...     ...          ...               ...   
1333   50       1  30.970         3       0  10600.54830                 0   
1334   18       0  31.920         0       0   2205.98080                 1   
1335   18       0  36.850         0       0   1629.83350                 0   
1336   21       0  25.800         0       0   2007.94500                 0   
1337   61       0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   gender            1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   int32  
 7   region_northwest  1338 non-null   int32  
 8   region_southeast  1338 non-null   int32  
 9   region_southwest  1338 non-null   int32  
dtypes: float64(2), int32(4), int64(4)
memory usage: 83.8 KB


### Model Training

In [15]:
df
x = df.drop('charges', axis = 1)
y = df['charges']

###### Train Test Split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=10)

In [17]:
lin_reg_model = LinearRegression()
lin_reg_model.fit(x_train, y_train)

LinearRegression()

In [18]:
lin_reg_model.coef_

array([  259.54736297,  -254.39763573,   353.03769217,   543.28925423,
       24124.10937703,   426.60645499,   234.60398263,  -469.52714954,
        -191.68328808])

In [19]:
lin_reg_model.intercept_

-13144.180622273087

### Evaluation

In [20]:
x_test.shape

(268, 9)

In [21]:
y_pred_test = lin_reg_model.predict(x_test)

In [22]:
y_test

7        7281.50560
999      5267.81815
1209    12347.17200
491     24513.09126
625      3736.46470
           ...     
271     42856.83800
695      3201.24515
1039    22493.65964
323     11566.30055
835      7160.33030
Name: charges, Length: 268, dtype: float64

In [23]:
y_pred_test[:5]

array([ 8116.8091336 ,  5925.54678115, 15364.0205027 , 11072.86668879,
        3806.86801357])

##### Testing Data Evaluation

In [24]:
y_pred_test = lin_reg_model.predict(x_test)

mse = mean_squared_error(y_test, y_pred_test)
print("MSE :",mse)

rmse = np.sqrt(mse)
print("RMSE :", rmse)

mae = mean_absolute_error(y_test, y_pred_test)
print("MAE :",mae)

r2_value = r2_score(y_test, y_pred_test)
print("R-squared :",r2_value)

MSE : 42730364.68387246
RMSE : 6536.846692700729
MAE : 4555.0985825133685
R-squared : 0.6953286838318307


### Training Data Evaluation

In [26]:
y_pred_train = lin_reg_model.predict(x_train)

mse = mean_squared_error(y_train, y_pred_train)
print("MSE :",mse)

rmse = np.sqrt(mse)
print("RMSE :", rmse)

mae = mean_absolute_error(y_train, y_pred_train)
print("MAE :",mae)

r2_value = r2_score(y_train, y_pred_train)
print("R-squared :",r2_value)

MSE : 35000135.31385896
RMSE : 5916.0912191969255
MAE : 4080.125542990985
R-squared : 0.7636624681782705


### Testing on User Data

In [29]:
age	= 58
gender = "female"
bmi	= 34.89
children = 2
smoker = "yes"
region = "southeast"



In [27]:
x_train.shape

(1070, 9)

In [28]:
x_test[45:46]

age  gender    bmi  children  smoker  region_northeast  region_northwest  \
800   42       0  26.18         1       0                 0                 0   

     region_southeast  region_southwest  
800                 1                 0

In [29]:
lin_reg_model.predict(x_test[45:46])

array([7073.09750803])

In [30]:
x_test[45:46].values

array([[42.  ,  0.  , 26.18,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ]])

In [31]:
lin_reg_model.predict(x_test[45:46].values)

array([7073.09750803])

In [32]:
test_array = np.zeros((1,9))

In [33]:
lin_reg_model.predict(test_array)

array([-13144.18062227])

In [34]:
# test_array = np.zeros((1,8))
# lin_reg_model.predict(test_array)

In [35]:
test_array = np.zeros((1,9))
test_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
column_names = x_train.columns
column_names

Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [37]:
label_enc_data = {"gender":{"male":1, "female":0},
                  "smoker" : {"yes":1, "no":0}}
label_enc_data

{'gender': {'male': 1, 'female': 0}, 'smoker': {'yes': 1, 'no': 0}}

In [39]:
age	= 58
gender = "male"
bmi	= 34.89
children = 2
smoker = "yes"
region = "southeast"

test_array[0,0] = age
test_array[0,1] = label_enc_data['gender'][gender]
test_array[0,2] = bmi
test_array[0,3] = children
test_array[0,4] = label_enc_data['smoker'][smoker]

region = f"region_{region}"

region_index = np.where(column_names == region)[0][0]
test_array[0,region_index] = 1
test_array

array([[58.  ,  1.  , 34.89,  2.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ]])

In [40]:
pred_value = lin_reg_model.predict(test_array)[0]
print("Predicted Value:",pred_value)

Predicted Value: 38713.81460983026


In [41]:
lin_reg_model

LinearRegression()

### Save Model

In [49]:
with open("Linear_reg_model.pkl", 'wb') as f:
    pickle.dump(lin_reg_model, f)

In [50]:
label_enc_data

{'gender': {'male': 1, 'female': 0}, 'smoker': {'yes': 1, 'no': 0}}

In [51]:
import json

In [52]:
with open("label_encoded_data.json", 'w') as f:
    json.dump(label_enc_data, f)

In [54]:
lin_reg_model.n_features_in_

9

In [55]:
lin_reg_model.feature_names_in_

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [56]:
import pandas as pd